### ISSUE TITLE
夜神模拟器的神奇bug

### ISSUE THREAD

**Issue by HideUsSaveUs** [Meowcolm024/FGO-Automata#42]
Traceback (most recent call last):
  File "12-31.py", line 5, in <module>
    fgo.quick_start(advance=True)
  File "E:\Butter\FGO-Automata\FGO-Automata-0.7.1\core\Automata.py", line 451, in quick_start
    self.select_checkpoint()
  File "E:\Butter\FGO-Automata\FGO-Automata-0.7.1\core\Automata.py", line 220, in select_checkpoint
    self.wait(self.checkpoint)
  File "E:\Butter\FGO-Automata\FGO-Automata-0.7.1\core\Automata.py", line 499, in wait
    while not util.standby(util.get_sh(self.shifts), pic):
  File "E:\Butter\FGO-Automata\FGO-Automata-0.7.1\core\util.py", line 49, in get_sh
    screenshot()
  File "E:\Butter\FGO-Automata\FGO-Automata-0.7.1\core\util.py", line 32, in screenshot
    os.system('adb shell screencap -p /sdcard/sh.png')
KeyboardInterrupt
或者不是bug是我电脑问题？

**Comment by HideUsSaveUs** [comment]
解决了，模拟器没法截图导致这个bug的发生，换了下机型就解决了
