### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by Baichuan-qiao** [Meowcolm024/FGO-Automata#65]
G:\FGO-Automata-master>python.exe name.py
Traceback (most recent call last):
  File "G:\FGO-Automata-master\name.py", line 1, in <module>
    from core.Automata import Automata
  File "G:\FGO-Automata-master\core\Automata.py", line 3, in <module>
    from core import util, crds
  File "G:\FGO-Automata-master\core\util.py", line 2, in <module>
    from cv2 import cv2
ImportError: Bindings generation error. Submodule name should always start with a parent module name. Parent name: cv2.cv2. Submodule name: cv2

**Comment by Meowcolm024** [comment]
可以试一下换成requirements.txt里面的opencv-python版本（4.4.0)，但我也好久没碰过这个项目了，不知道还能不能跑
